blueprint:
  name: Sonoff TRV PID
  description: Automation to enable PID control of Sonoff TRV in conjuction with Smart Thermostat PID (available from HACS)
  domain: automation
  input:
    thermostat_value:
      name: Thermostat Value
      selector: 
        entity:
          filter:
            - domain: input_number
  
    max_valve_opening:
      name: Max Valve Opening Position
      selector: 
        entity:
          filter:
            - domain: number
      
    max_valve_closing:
      name: Max Valve Closing Position
      selector: 
        entity:
          filter:
            - domain: number

variables:
  thermostat_value: !input 'thermostat_value'
  max_valve_opening: !input 'max_valve_opening'
  max_valve_closing: ! input 'max_valve_closing'
  
triggers: 
  trigger: state
  entity_id: input_number.trv_valve_position 

actions:
  action: number.set_value
  data: 
    value: "{{100.0-states('input_number.trv_valve_position')| float}}" 
  target: 
    entity_id: number.trv_valve_closing_degree 

  action: number.set_value
  data: 
    value: "{{states('input_ number.trv_valve_position')| float+5}}" 
  target:
    entity_id: number.trv_valve_opening_degree
  mode: single
