blueprint:
  name: Sonoff TRV Offset
  description: Automatically adjust the offset of the temperature sensor using an external sensor.
  domain: automation
  input:
    climate_entity:
      name: Sonoff TRV Entity
      selector:
        entity:
          filter:
            - domain: climate
    sensor_entity:
      name: External Temp Sensor
      selector:
        entity:
          filter:
            - domain: sensor
            - device_class: temperature
  
mode: single
max_exceeded: silent
  
variables:
  trv_entity: !input 'climate_entity'
  temp_entity: !input 'sensor_entity'
  sensor_temp: "{{ states(temp_entity) | round(1) }}"
  trv_temp: "{{ state_attr(trv_entity, 'local_temperature') | round(1) }}"
  trv_offset: "{{ state_attr(trv_entity, 'local_temperature_calibration') | round(1) }}"
  friendly_name: "{{ state_attr(trv_entity, 'friendly_name')}}"
  
trigger:
  - platform: state
    entity_id: !input 'sensor_entity'
    for:
      seconds: 15

condition:
  condition: template
  value_template: "{{ sensor_temp != trv_temp }}"

action:
  - service: mqtt.publish
    data_template:
      topic_template: "zigbee2mqtt/{{ friendly_name }}/set"
      payload_template: '{"local_temperature_calibration":{{ (sensor_temp - (trv_temp - trv_offset)) | round(1) }}}'
  - delay: 5
